module.exports = {
  getok: [200, 'ok'],
  postok: [201, 'success'],
  diffAppId: [427, 'Different appIds'],
  missQuery: [428, 'Missing Query String!'],
  wxlogin: [429, 'wechat login error!'],
  checkraw: [430, `You have't permission`],
  checktoken: [431, 'Invalid token'],
  typeExist: [432, 'You are already a teacher or a student'],
  passErr: [433, 'Password error'],
  integralNE: [434, 'Integral is not enough'],
  goodsOff: [435, 'This goods is now off the shelves'],
  noText: [436, 'Text cannot be empty'],
  alreadySigned: [437, `You've already signed in`],
  notYours: [438, `It's not yours`],
  noPermiss: [439, 'No permissions to create the new one'],
  formatIncorr: [441, 'The format is incorrect'],
  other: [442, 'Other'],
  other: [443, 'Other'],
  other: [445, 'Other'],
  failed: [444, 'failed'],
  checkuserId: [440, 'Not found this userId'],
  nothing: [404, 'Not found'],
  serverErr: [500, 'Server error']
}